/////////////////////////////////////////////////////////////////////////
// Javascript file generated by ctc2html v6.0 at Mon Apr 1 15:55:36 2019
// Copyright (c) 2006-2013 Testwell Oy
// Copyright (c) 2013-2016 Verifysoft Technology GmbH
/////////////////////////////////////////////////////////////////////////
target=location.hash;

function highlight(row, a, b) {
   var cl;
   var cells;
   row.style.cursor = 'pointer';
   if (row.tagName != "TR") {
      row = row.parentNode;
      if (row.tagName != "TR") {
         row = row.parentNode;
      }
   }
   cells = row.parentNode.rows[row.rowIndex - a - 1].getElementsByTagName("td");
   for (var i = 0; i < cells.length; i++) {
      cl = cells[i].getAttribute("class");
      if (cl != null) {
         cells[i].setAttribute("class", cl.replace(/profile/, "highlight"));
      } else {
	 cl = cells[i].getAttribute("className");
	 if (cl != null) {
	     cells[i].setAttribute("className", cl.replace(/profile/, "highlight"));
	 }
      }
   }
   cells = row.parentNode.rows[row.rowIndex - b - 1].getElementsByTagName("td");
   for (var i = 0; i < cells.length; i++) {
      cl = cells[i].getAttribute("class");
      if (cl != null) {
         cells[i].setAttribute("class", cl.replace(/profile/, "highlight"));
      } else {
	 cl = cells[i].getAttribute("className");
	 if (cl != null) {
	     cells[i].setAttribute("className", cl.replace(/profile/, "highlight"));
	 }
      }
   }
   cells = row.parentNode.rows[row.rowIndex - a - 1].getElementsByTagName("span");
   for (var i = 0; i < cells.length; i++) {
      cl = cells[0].getAttribute("class");
      if (cl != null) {
         cells[0].setAttribute("class", cl.replace(/profile/, "highlight"));
      } else {
	 cl = cells[0].getAttribute("className");
	 if (cl != null) {
	     cells[0].setAttribute("className", cl.replace(/profile/, "highlight"));
	 }
      }
   }
   cells = row.parentNode.rows[row.rowIndex - b - 1].getElementsByTagName("span");
   for (var i = 0; i < cells.length; i++) {
      cl = cells[0].getAttribute("class");
      if (cl != null) {
         cells[0].setAttribute("class", cl.replace(/profile/, "highlight"));
      } else {
	 cl = cells[0].getAttribute("className");
	 if (cl != null) {
	     cells[0].setAttribute("className", cl.replace(/profile/, "highlight"));
	 }
      }
   }
}

function unhighlight(row, a, b) {
   var cl;
   var cells;
   if (row.tagName != "TR") {
      row = row.parentNode;
      if (row.tagName != "TR") {
         row = row.parentNode;
      }
   }
   cells = row.parentNode.rows[row.rowIndex - a - 1].getElementsByTagName("td");
   for (var i = 0; i < cells.length; i++) {
      cl = cells[i].getAttribute("class");
      if (cl != null) {
         cells[i].setAttribute("class", cl.replace(/highlight/, "profile"));
      } else {
	 cl = cells[i].getAttribute("className");
	 if (cl != null) {
	     cells[i].setAttribute("className", cl.replace(/highlight/, "profile"));
	 }
      }
   }
   cells = row.parentNode.rows[row.rowIndex - b - 1].getElementsByTagName("td");
   for (var i = 0; i < cells.length; i++) {
      cl = cells[i].getAttribute("class");
      if (cl != null) {
         cells[i].setAttribute("class", cl.replace(/highlight/, "profile"));
      } else {
	 cl = cells[i].getAttribute("className");
	 if (cl != null) {
	     cells[i].setAttribute("className", cl.replace(/highlight/, "profile"));
	 }
      }
   }
   cells = row.parentNode.rows[row.rowIndex - a - 1].getElementsByTagName("span");
   for (var i = 0; i < cells.length; i++) {
      cl = cells[i].getAttribute("class");
      if (cl != null) {
         cells[0].setAttribute("class", cl.replace(/highlight/, "profile"));
      } else {
	 cl = cells[0].getAttribute("className");
	 if (cl != null) {
	     cells[0].setAttribute("className", cl.replace(/highlight/, "profile"));
	 }
      }
   }
   cells = row.parentNode.rows[row.rowIndex - b - 1].getElementsByTagName("span");
   for (var i = 0; i < cells.length; i++) {
      cl = cells[i].getAttribute("class");
      if (cl != null) {
         cells[0].setAttribute("class", cl.replace(/highlight/, "profile"));
      } else {
	 cl = cells[0].getAttribute("className");
	 if (cl != null) {
	     cells[0].setAttribute("className", cl.replace(/highlight/, "profile"));
	 }
      }
   }
}

function load_profile() {
   if (target == "#a1") {
      parent.index_profile.location = "indexC.html#a1";
      parent.profile.location = "indexD1.html";
   }
   if (target == "#a2") {
      parent.index_profile.location = "indexC.html#a2";
      parent.profile.location = "indexD2.html";
   }
   if (target == "#a3") {
      parent.index_profile.location = "indexC.html#a3";
      parent.profile.location = "indexD3.html";
   }
   if (target == "#a4") {
      parent.index_profile.location = "indexC.html#a4";
      parent.profile.location = "indexD4.html";
   }
   if (target == "#a5") {
      parent.index_profile.location = "indexC.html#a5";
      parent.profile.location = "indexD5.html";
   }
}

function load_funcs() {
   if (target == "#ad1") {
      parent.index_funcs.location = "indexH.html#ad1";
      parent.functions.location = "indexB1.html";
   }
   if (target == "#ad2") {
      parent.index_funcs.location = "indexH.html#ad2";
      parent.functions.location = "indexB2.html";
   }
   if (target == "#ad2") {
      parent.index_funcs.location = "indexH.html#ad2";
      parent.functions.location = "indexB2.html";
   }
   if (target == "#ad2") {
      parent.index_funcs.location = "indexH.html#ad2";
      parent.functions.location = "indexB2.html";
   }
   if (target == "#ad3") {
      parent.index_funcs.location = "indexH.html#ad3";
      parent.functions.location = "indexB3.html";
   }
}

function load_untested() {
   if (target == "#ufi1") {
      parent.index_untested.location = "indexI.html#ufi1";
      parent.untested.location = "indexU.html";
   }
   if (target == "#ufi2") {
      parent.index_untested.location = "indexI.html#ufi2";
      parent.untested.location = "indexU.html";
   }
   if (target == "#ufi3") {
      parent.index_untested.location = "indexI.html#ufi3";
      parent.untested.location = "indexU.html";
   }
   if (target == "#ufi4") {
      parent.index_untested.location = "indexI.html#ufi4";
      parent.untested.location = "indexU.html";
   }
   if (target == "#ufi5") {
      parent.index_untested.location = "indexI.html#ufi5";
      parent.untested.location = "indexU.html";
   }
}
